// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizAPP.Data;

#nullable disable

namespace QuizAPP.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230428182927_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuizAPP.Models.QuizModels", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Javob1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Javob2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Savol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tugri_Javob")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Quiz");
                });
#pragma warning restore 612, 618
        }
    }
}
